return {{
  [[a ring]],
  [[a ring]],
  [[a necklace]],
  [[a necklace]],
  [[a shirt]],
  [[a hat]],
  [[a pair of pants]],
  [[some boots]],
  [[some gloves]],
  [[a coat]],
  [[a belt]],
  [[a bracelet]],
  [[a bracelet]],
  [[a pencil]],
  [[a notebook]],
  [[a tail ring]],
  [[an eraser]],
  [[a rule book]],
  [[a golden d20]],
  [[something floaty]],
  [[something wavy]],
  [[something bobby]],
  [[something artifacty]],
},}
