return {{
  [ [[On]] ] = [[false]],
  [ [[Kill]] ] = [[false]],
  [ [[Target]] ] = [[none]],
  [ [[Area]] ] = [[none]],
  [ [[Rate]] ] = [[4]],
  [ [[Threshold]] ] = [[85]],
  [ [[Wimpy]] ] = [[50]],
  [ [[Bugout]] ] = [[40]],
  [ [[EmergencyTrigger]] ] = [[60]],
  [ [[EmergencyAction]] ] = [[flee]],
  [ [[Auto]] ] = [[none]],
  [ [[OffAuto]] ] = [[none]],
  [ [[OffRate]] ] = [[60]],
  [ [[Disarm]] ] = [[none]],
  [ [[Butcher]] ] = [[false]],
  [ [[Soup]] ] = [[true]],
  [ [[Skin]] ] = [[false]],
},}
