return {{
  [ [[name]] ] = {
    [ [[Race]] ] = [[Human]],
    [ [[Name]] ] = [[Tim]],
    [ [[PercToLevel]] ] = [[99]],
    [ [[Class]] ] = [[civilian]],
    [ [[Level]] ] = [[100]],
  },
  [ [[character]] ] = {
    [ [[Iron]] ] = [[false]],
    [ [[Str]] ] = [[25]],
    [ [[StrMax]] ] = [[25]],
    [ [[Int]] ] = [[25]],
    [ [[IntMax]] ] = [[25]],
    [ [[Wis]] ] = [[25]],
    [ [[WisMax]] ] = [[25]],
    [ [[Dex]] ] = [[25]],
    [ [[DexMax]] ] = [[25]],
    [ [[Con]] ] = [[25]],
    [ [[ConMax]] ] = [[25]],
    [ [[Hunger]] ] = [[50]],
    [ [[HungerMax]] ] = [[100]],
    [ [[Thirst]] ] = [[50]],
    [ [[ThirstMax]] ] = [[100]],
    [ [[Trains]] ] = [[112]],
    [ [[HeroPoints]] ] = [[1024]],
    [ [[Age]] ] = [[55]],
    [ [[Weight]] ] = [[100]],
    [ [[Sex]] ] = [[male]],
    [ [[Religion]] ] = [[xaos]],
    [ [[Caste]] ] = [[dung]],
    [ [[Favor]] ] = [[1500]],
    [ [[Affliction]] ] = [[none]],
    [ [[AfflictionTier]] ] = [[none]],
    [ [[AfflictionTime]] ] = [[0]],
  },
  [ [[equipment]] ] = {
    [[a ring]],
    [[a ring]],
    [[a necklace]],
    [[a necklace]],
    [[a shirt]],
    [[a hat]],
    [[a pair of pants]],
    [[some boots]],
    [[some gloves]],
    [[a coat]],
    [[a belt]],
    [[a bracelet]],
    [[a bracelet]],
    [[a pencil]],
    [[a notebook]],
    [[a tail ring]],
    [[an eraser]],
    [[a rule book]],
    [[a golden d20]],
    [[something floaty]],
    [[something wavy]],
    [[something bobby]],
    [[something artifacty]],
  },
  [ [[inventory]] ] = {
    [ [[Silver]] ] = [[901]],
    [ [[Gold]] ] = [[1]],
    [ [[eqWeight]] ] = [[90]],
    [ [[eqWeightMax]] ] = [[1000]],
    [ [[Items]] ] = [[1]],
    [ [[ItemsMax]] ] = [[100]],
    [ [ [[Artifacts]] ] = [[1]],
    [ [[ArtifactsMax]] ] = [[2]],
    [ [[Inventory]] ] = {2}, {
      [1] = [[a map]],
      [2] = [[a ball of light]],
    },
  },
  [ [[defenses]] ] = {
    [ [[ArmorClass]] ] = [[1708]],
    [ [[ArmorPerc]] ] = [[31]],
    [ [[Warding]] ] = [[1183]],
    [ [[WardingPerc]] ] = [[22]],
    [ [[Saves]] ] = [[152]],
    [ [[SlashRes]] ] = [[15]],
    [ [[BashRes]] ] = [[20]],
    [ [[PierceRes]] ] = [[15]],
    [ [[FireRes]] ] = [[3]],
    [ [[ColdRes]] ] = [[3]],
    [ [[MentalRes]] ] = [[0]],
    [ [[MagicRes]] ] = [[0]],
    [ [[LightRes]] ] = [[0]],
    [ [[NegativeRes]] ] = [[10]],
    [ [[HolyRes]] ] = [[0]],
    [ [[UnholyRes]] ] = [[0]],
    [ [[LightningRes]] ] = [[3]],
    [ [[SoundRes]] ] = [[0]],
    [ [[AcidRes]] ] = [[3]],
    [ [[PoisonRes]] ] = [[0]],
    [ [[DiseaseRes]] ] = [[0]],
    [ [[Dodge]] ] = [[51]],
    [ [[DodgeFactor]] ] = [[99]],
    [ [[Parry]] ] = [[0]],
    [ [[SecondaryParry]] ] = [[0]],
    [ [[UnarmedBlock]] ] = [[95]],
    [ [[ShieldBlock]] ] = [[0]],
    [ [[LowerRightParry]] ] = [[0]],
    [ [[LowerLeftParry]] ] = [[0]],
    [ [[TailParry]] ] = [[0]],
    [ [[Phase]] ] = [[0]],
    [ [[ShieldCapacity]] ] = [[500]],
    [ [[ShieldReduction]] ] = [[25]],
    [ [[ShieldRecharge]] ] = [[100]],
    [ [[HPRegen]] ] = [[100]],
    [ [[HealMod]] ] = [[100]],
    [ [[ManaRegen]] ] = [[100]],
  },
  [ [[offense]] ] = {
    [ [[Hitroll]] ] = [[10]],
    [ [[DefenseBreak]] ] = [[13]],
    [ [[Damroll]] ] = [[15]],
    [ [[Damage]] ] = [[17]],
    [ [[Speed]] ] = [[17]],
    [ [[TotalSpeed]] ] = [[17]],
    [ [[CharacterDamage]] ] = [[100]],
    [ [[SpellDamage]] ] = [[100]],
    [ [[CritChance]] ] = [[15]],
    [ [[CritDamage]] ] = [[110]],
    [ [[Style]] ] = [[Normal]],
    [ [[Tactics]] ] = [[default]],
  },
  [ [[casting]] ] = {
    [ [[Base]] ] = [[100]],
    [ [[Necro]] ] = [[101]],
    [ [[Abjur]] ] = [[102]],
    [ [[Alter]] ] = [[103]],
    [ [[Conju]] ] = [[104]],
    [ [[Encha]] ] = [[105]],
    [ [[Divin]] ] = [[106]],
    [ [[Illus]] ] = [[107]],
    [ [[Invoc]] ] = [[108]],
    [ [[Begui]] ] = [[109]],
    [ [[Relig]] ] = [[110]],
    [ [[Malad]] ] = [[111]],
  },
  [ [[traits]] ] = {
    [[overpowered]],
  },
  [ [[traitsDetail]] ] = {
    [ [[bruiser]] ] = [[You are powerfully, and a force to be reckoned with.]],
    [ [[genesis]] ] = [[You don't stay down and putting you down is hard.]],
    [ [[chosen]] ] = [[You are intune with the ways of combat.]],
    [ [[gifted]] ] = [[Your mind is your weapon and it is deadly.]],
    [ [[attuned]] ] = [[You have mana flowing in your blood.]],
    [ [[paragon]] ] = [[You radiate charisma and are a natural leader.]],
    [ [[reborn]] ] = [[You posess skills from outside your profession.]],
    [ [[tinker]] ] = [[Your gifted at utilizing magical items.]],
    [ [[errant]] ] = [[You have gained knowledge of secret arts.]],
    [ [[overpowered]] ] = [[You have ascended above others of your race.]],
  },
  [ [[boons]] ] = {
    [[super strength]],
  },
  [ [[boonsDetail]]] = {
    [ [[free gestures]] ] = [[Allows casting without hand limitations.]],
    [ [[enhanced criticals]] ] = [[Increased critical strike chance and damage.]],
    [ [[super strength]] ] = [[Greatly increased strength and disarm protection.]],
    [ [[mad carver]] ] = [[Increases zap and health, mana gained from zap.]],
    [ [[deflection]] ] = [[Deflect attacks when used with kinetic command.]],
    [ [[enhanced dispel]] ] = [[Improves dispel, soften defense, weaken, and slow.]],
    [ [[cruelty]] ] = [[Increased dam when opponent can't see you or is knocked down.]],
    [ [[companion]] ] = [[All weapons are daggers for backstab and lethality.]],
    [ [[shrike]] ] = [[New attacks and style, allows backstab and impale.]],
    [ [[pestilence]] ] = [[Unleashes new powers for poison and plague spells.]],
    [ [[juggernaut]] ] = [[Grants bash skill and additional bash power.]],
    [ [[spright]] ] = [[This shield can be thrown and returns to user.]],
    [ [[artificer]] ] = [[Bash procs weapon magic effects, improves magic proc rates.]],
    [ [[overpowering strikes]] ] = [[Size and strength let you overwhelm parries.]],
    [ [[bloodthirst]] ] = [[Slash and pierce damage grant a small heal based on damage.]],
    [ [[mana burn]] ] = [[Weapon deals additional damage based on victim's mana regen.]],
    [ [[defense piercing]] ] = [[Weapon has chance to pierce a defense.]],
    [ [[gamblers heart]] ] = [[Increase parry and unarmed block vs critical strikes.]],
    [ [[savagery]] ] = [[Converts normal attacks into savage attacks.]],
    [ [[enhanced fire]] ] = [[Single target fire spells do AOE and fire damage.]],
    [ [[frost heart]] ] = [[ Heal based on cold damage and improves cold damage.]],
    [ [[damaging heals]] ] = [[Select heal spells also do damage to opponents.]],
    [ [[unarmed boost]] ] = [[Unarmed has a chance to pierce a defense, and improves unarmed dam.]],
    [ [[absorption]] ] = [[Can absorb magic attacks when equipped with kinetic command.]],
    [ [[discharger]] ] = [[Can generate spells when equiped with kinetic command.]],
    [ [[void call]] ] = [[Phase attacks will attempt to blind the attacker.]],
    [ [[seeker]] ] = [[Improves base effectiveness of hitroll and hitroll growth.]],
    [ [[mana force]] ] = [[Improves casting based on mana.]],
    [ [[kinetic boost]] ] = [[Improves kinetic offense.]],
    [ [[living armor]] ] = [[Increases effectiveness of damage roll based on physical armor.]],
    [ [[resilience]] ] = [[Increases amount of healing received based on armor.]],
    [ [[emulation]] ] = [[Gives a chance to cast a spell again at greatly increased levels.]],
    [ [[blood magic]] ] = [[Cast at a higher level but lose hp per combat round.]],
    [ [[lightning nature]] ] = [[Improves critical chance and doubles critical damage from lightning.]],
    [ [[acid burn]] ] = [[Acid damage gives victims an acid vulnerability based on damage done.]],
    [ [[enhanced speed]] ] = [[Gives additional speed when equipped with kinetic command.]],
    [ [[spell catching]] ] = [[Allows blocking of spells with unarmed block.]],
    [ [[warding enhancement]] ] = [[Adds a third of your armor class to your warding.]],
  },
  [ [[theme]] ] = {
    [ [[Font]] ] = [[Consolas]],
    [ [[FontSize]] ] = [[10]],
    [ [[FontColor]] ] = [[black]],
    [ [[BorderRadius]] ] = [[5]],
    [ [[BorderWidth]] ] = [[1]],
    [ [[BorderStyle]] ] = [[Solid]],
    [ [[Margin]] ] = [[5]],
    [ [[Padding]] ] = [[5]],
    [ [[Color1]] ] = [[DimGrey]],
    [ [[Color2]] ] = [[LightGrey]],
    [ [[Color3]] ] = [[white]],
    [ [[Color4]] ] = [[black]],
    [ [[Color5]] ] = [[yellow]],
    [ [[Color6]] ] = [[DarkGoldenrod]],
  },
  [ [[colors]] ] = {
    [[DarkKhaki]],
    [[purple]],
    [[DarkGoldenrod]],
    [[PaleGreen]],
    [[linen]],
    [[azure]],
    [[AliceBlue]],
    [[OrangeRed]],
    [[LightSalmon]],
    [[SlateBlue]],
    [[OliveDrab]],
    [[honeydew]],
    [[chocolate]],
    [[OldLace]],
    [[FloralWhite]],
    [[tomato]],
    [[gold]],
    [[LightSlateBlue]],
    [[DarkSlateGray]],
    [[grey]],
    [[CadetBlue]],
    [[NavajoWhite]],
    [[PaleVioletRed]],
    [[LightCoral]],
    [[bisque]],
    [[DarkOrchid]],
    [[AntiqueWhite]],
    [[MediumSpringGreen]],
    [[DarkOliveGreen]],
    [[PaleGoldenrod]],
    [[coral]],
    [[red]],
    [[DimGrey]],
    [[ForestGreen]],
    [[YellowGreen]],
    [[yellow]],
    [[BlueViolet]],
    [[BlanchedAlmond]],
    [[WhiteSmoke]],
    [[white]],
    [[HotPink]],
    [[wheat]],
    [[DimGray]],
    [[violet]],
    [[RoyalBlue]],
    [[ivory]],
    [[LightGrey]],
    [[turquoise]],
    [[khaki]],
    [[tan]],
    [[SpringGreen]],
    [[SeaGreen]],
    [[SteelBlue]],
    [[MediumSlateBlue]],
    [[MintCream]],
    [[snow]],
    [[SlateGrey]],
    [[DodgerBlue]],
    [[DarkOrange]],
    [[SlateGray]],
    [[DeepSkyBlue]],
    [[cyan]],
    [[NavyBlue]],
    [[sienna]],
    [[plum]],
    [[brown]],
    [[gainsboro]],
    [[DeepPink]],
    [[SandyBrown]],
    [[salmon]],
    [[MediumPurple]],
    [[SaddleBrown]],
    [[RosyBrown]],
    [[LightSteelBlue]],
    [[black]],
    [[VioletRed]],
    [[PowderBlue]],
    [[DarkSeaGreen]],
    [[navy]],
    [[cornsilk]],
    [[orange]],
    [[LightPink]],
    [[CornflowerBlue]],
    [[PeachPuff]],
    [[LightSkyBlue]],
    [[DarkGreen]],
    [[GreenYellow]],
    [[DarkSlateGrey]],
    [[PapayaWhip]],
    [[PaleTurquoise]],
    [[pink]],
    [[orchid]],
    [[LemonChiffon]],
    [[green]],
    [[peru]],
    [[gray]],
    [[DarkSlateBlue]],
    [[MediumAquamarine]],
    [[moccasin]],
    [[MistyRose]],
    [[thistle]],
    [[DarkViolet]],
    [[MediumVioletRed]],
    [[magenta]],
    [[beige]],
    [[SkyBlue]],
    [[maroon]],
    [[LavenderBlush]],
    [[LawnGreen]],
    [[MediumOrchid]],
    [[MediumBlue]],
    [[MediumTurquoise]],
    [[LimeGreen]],
    [[LightYellow]],
    [[LightSlateGrey]],
    [[LightBlue]],
    [[LightSlateGray]],
    [[seashell]],
    [[LightSeaGreen]],
    [[DarkTurquoise]],
    [[LightGoldenrod]],
    [[LightCyan]],
    [[chartreuse]],
    [[MediumSeaGreen]],
    [[lavender]],
    [[blue]],
    [[MidnightBlue]],
    [[IndianRed]],
    [[LightGray]],
    [[goldenrod]],
    [[GhostWhite]],
    [[firebrick]],
    [[LightGoldenrodYellow]],
    [[DarkSalmon]],
    [[aquamarine]],
    [[burlywood]],
  },
}}
